import { Request, Response, NextFunction } from "express";
import { validationResult } from "express-validator";

/**
* Validation middleware for Express.
*
* Checks for validation errors generated by `express-validator`
* in the current request. If so, returns a `400 Bad Request` with the
* list of errors. If not, passes control to the next middleware/controller.
*/

export const validate = (req: Request, res: Response, next: NextFunction) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) 
        return res.status(400).json({ errors: errors.array() });
    next();
};

export const errorHandler = (err: any, _req: Request, res: Response, _next: NextFunction) => {
    console.error(err);
    res.status(err.status || 500).json({ message: err.message || "Internal server error" });
};